services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    restart: unless-stopped

    ports:
      - "80:6789"

    volumes:
      - /volume2/docker/iptv/iptv-api/config:/iptv-api/config
      - /volume2/docker/iptv/iptv-api/output:/iptv-api/output

    environment:
      PUBLIC_SCHEME: "http"
      # Replace with your public domain or IP
      PUBLIC_DOMAIN: "http://2560.eu.org"
      PUBLIC_PORT: "80"
      NGINX_HTTP_PORT: "6789"
      CDN_URL: ""
